### ISSUE TITLE
Can't enter into playlist containing specific video

### ISSUE THREAD

**Issue by AlexNk** [jdf76/plugin.video.youtube#801] opened 2020-04-24 16:40 UTC
Video: https://www.youtube.com/watch?v=KR4DjYczINM

Error from logs:
```
2020-04-24 19:27:40.081 T:140247348258560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data u'2013-12-06T16:40:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 464, in _on_channel_playlist
                                                result.extend(v3.response_to_items(self, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 269, in response_to_items
                                                result.extend(_process_list_response(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/v3.py", line 253, in _process_list_response
                                                live_details=is_upcoming, use_play_data=use_play_data)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 292, in update_video_infos
                                                video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt']))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/datetime_parser.py", line 176, in strptime
                                                return datetime(*time.strptime(s, fmt)[:6])
                                              File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                            ValueError: time data u'2013-12-06T16:40:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            -->End of Python script error report<--
```

**Comment by anxdpanic** [comment] 2020-04-24 16:58
Duplicate of #783 
Fixed in beta1 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev

**Closed by anxdpanic** 2020-04-24 16:58 UTC
