### ISSUE TITLE
Exception after login

### ISSUE THREAD

**Issue by maxberghammer** [jdf76/plugin.video.youtube#742] opened 2020-02-28 15:45 UTC
Today I created a new google-account and wanted to use this account in the youtube-addon. Unfortunately I get an "Youtube-error" after I entered the 2 codes on the google/device-page. Using another (older) account works perfectly, but the newly created one doesn't. The kodi-log says the following:
```
2020-02-28 15:55:01.432 T:1764770528  NOTICE: [plugin.video.youtube] Running: YouTube (6.6.0) on Leia (Kodi-18.2) with Python 2.7.13
                                            	Path: /
                                            	Params: {}
2020-02-28 15:55:01.852 T:1764770528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate
                                                result = method(context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 132, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1485, in on_root
                                                playlists = resource_manager.get_related_playlists(channel_id='mine')
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 183, in get_related_playlists
                                                result = self._update_channels([channel_id])
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 50, in _update_channels
                                                channel_id = items[0]['id']
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-02-28 15:55:02.045 T:1472189152   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
2020-02-28 15:55:02.051 T:1901990752   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed
```
I'm using my own ApiKey (I tried an existing one and one newly created for the new account - makes no difference) and run Kodi 18.2 on a raspi 3B+ with raspian stretch and all updates installed. I already tried subscribing to a youtube-channel, as I thought this would be the problem when I looked at the logs - Still no success. Do I have to change something on my google account?

**Comment by Jurik-Phys** [comment] 2020-02-28 18:08
A few days ago I was created ApiKey and youtube-addon worked fine. But today I got the same error. Update addon and os for last version don't help me.  I run Kodi (18.5) on raspberry PI 3B+ with OSMC.

```
osmc@rpi-room:~/.kodi/temp$ grep Kodi ~/.kodi/temp/kodi.log | head -3
2020-02-28 13:52:17.167 T:1915790896  NOTICE: Starting Kodi (18.5). Platform: Linux ARM (Thumb) 32-bit
2020-02-28 13:52:17.167 T:1915790896  NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
2020-02-28 13:52:17.167 T:1915790896  NOTICE: Kodi compiled 2020-01-29 by GCC 6.3.0 for Linux ARM (Thumb) 32-bit version 4.9.110 (264558)
osmc@rpi-room:~/.kodi/temp$ grep VERSION_ID /etc/os-release
VERSION_ID="2020.01-2"
```

```
2020-02-28 19:58:12.637 T:1516233440  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0~alpha1) on Leia (Kodi-18.5) with Python 2.7.13
                                                Path: /
                                                Params: {}
2020-02-28 19:58:12.746 T:1516233440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 99, in navigate
                                                result = method(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 132, in _internal_root
                                                return self.on_root(context, re_match)
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 1486, in on_root
                                                playlists = resource_manager.get_related_playlists(channel_id='mine')
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 184, in get_related_playlists
                                                result = self._update_channels([channel_id])
                                              File "/home/osmc/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/resource_manager.py", line 51, in _update_channels
                                                channel_id = items[0]['id']
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-02-28 19:58:12.955 T:1406120672   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/
2020-02-28 19:58:12.957 T:1915790896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/) failed 

```

**Comment by lsborg** [comment] 2020-02-28 23:48
Same error here, kodi 18.5, youtube 6.6.0, librelec, pi 1 model B.

**Comment by anxdpanic** [comment] 2020-02-29 00:53
Can one of you try https://github.com/jdf76/plugin.video.youtube/releases/download/6.7.0-dev/plugin.video.youtube-6.7.0.alpha2.zip and please post the debug log even if it works. I'm unable to reproduce this so I've added logging to see what is being returned in this case, and hopefully find a better solution. Thanks 👍

**Comment by guidosarducci** [comment] 2020-02-29 00:54
I too have the same error, also using Kodi 18.5 with Youtube v6.6.0. I am using the same personal API keys I've been successfully using for years. Nothing has changed apart from the most recent update to the addon.

**Comment by guidosarducci** [comment] 2020-02-29 01:10
> Can one of you try https://github.com/jdf76/plugin.video.youtube/releases/download/6.7.0-dev/plugin.video.youtube-6.7.0.alpha2.zip and please post the debug log even if it works. I'm unable to reproduce this so I've added logging to see what is being returned in this case, and hopefully find a better solution. Thanks +1

@anxdpanic It works without errors. I can see my own subscriptions so it must me authenticating properly. Thanks very much... What changed?

**Comment by anxdpanic** [comment] 2020-02-29 01:15
I'm guessing My Channel doesn't show up for you now though? 
I won't know what changed really until I can get a debug log with the alpha2 zip since I'm unable to reproduce.

**Comment by guidosarducci** [comment] 2020-02-29 02:16
OK, I tested by selecting 'My Subscriptions', then 'My Channel -> Playlists' (it does show up), and captured the debug log below. Hope that helps.

[youtube.log](https://github.com/jdf76/plugin.video.youtube/files/4269801/youtube.log)

**Comment by anxdpanic** [comment] 2020-02-29 02:25
Thanks @guidosarducci 
It looks like some stuff will likely not work, the logging confirmed it's likely a change to something YouTube's end only affecting some accounts. YouTube normally returns a channel id for for 'mine', which it's unable to find according to the logs.
Will look into it more next chance I get though.

**Comment by lsborg** [comment] 2020-02-29 02:27
Thanks @anxdpanic the alpha is working here too.

**Comment by Jurik-Phys** [comment] 2020-02-29 08:44
I updated plugin.video.youtube-6.7.0.alpha1 to plugin.video.youtube-6.7.0.alpha2. Authenticating now work properly. I get list of video from "My Subscriptions"/"Мои подписки" and video from this list played.  Log attached. Thanks for work!

[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/4270077/kodi.log)

**Comment by Jurik-Phys** [comment] 2020-02-29 09:44
After playing video thourgh one hour and stoped it I don't get list of video from "My Subscriptions"/"Мои подписки". I get only clean list with zero items. Log attached.

[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/4270132/kodi.log)

**Comment by maxberghammer** [comment] 2020-02-29 13:09
@anxdpanic I changed the code in the python-file directly in the way you did it in your alpha. Seems to work perfectly! Thx!

**Comment by anxdpanic** [comment] 2020-02-29 14:40
@Jurik-Phys 
Try `Settings - Maintenance - Reset access manager` 
if that fails `Settings - Maintenance - Delete access_manager.json`
if that fails manually delete `userdata/addon_data/plugin.video.youtube/access_manager.json`

**Comment by Jurik-Phys** [comment] 2020-02-29 17:59
> Try Settings - Maintenance - Reset access manager
After reset I did two stage authorization and list of video worked.

**Comment by lameventanas** [comment] 2020-03-04 21:59
@anxdpanic I have the same problem here, and I don't see any `Maintenance` under `Settings`.

**Comment by anxdpanic** [comment] 2020-03-04 22:26
@lameventanas It's there you just need to scroll the categories.

**Comment by lameventanas** [comment] 2020-03-04 22:36
I'm using Kodi 18.5 with the Confluence theme.
Under Settings I have: Player, Media, Games, PVR & Live TV, Add-ons, Service, Interface and System.

**Comment by anxdpanic** [comment] 2020-03-04 22:38
You need to open the `Context Menu` or `Information`, on the YouTube add-on and choose Settings there.

**Comment by lameventanas** [comment] 2020-03-04 22:44
Oh I see, I thought it was a global cache thing that had to be reset.

Is there a way to prevent this in the future or make it more automatic? Maybe by more checks on what is returned by Youtube?

**Comment by anxdpanic** [comment] 2020-03-04 22:46
Without the debug log, I don't even know what issue you were experiencing.

**Comment by lameventanas** [comment] 2020-03-04 22:49
My debug log looks exactly like the one posted here, eg: IndexError: list index out of range after json_data.get() returns an empty list and there is no check for that.

**Comment by anxdpanic** [comment] 2020-03-04 22:57
Ah, that was fixed in the alphas. So I didn't think of Maintenance being related to that

Up until recently this area of code worked for everyone, YouTube made a change and now the same information isn't available for all accounts. This caused the error.
But yes, it is already fixed. 

You can find the beta https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.0-dev

**Comment by lameventanas** [comment] 2020-03-04 23:29
Thanks!
If I want to backport it, can i just apply ed1e160a514ffb1a73d347b773e710c4b9c6dea6 or is it more complicated than this?

**Comment by anxdpanic** [comment] 2020-03-04 23:30
that's all that is required for that particular fix

**Comment by lameventanas** [comment] 2020-03-05 00:10
Thanks for your prompt communication, and great work in this addon.  It is working now :)
I'm looking forward to 6.7 being released!

**Closed** 2020-05-09 23:15 UTC
