### ISSUE TITLE
Audio only Error (Audio only Off, kodi.log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#475] opened 2018-11-15 17:46 UTC
_Translator:_
Instead of this movie:
https://youtu.be/FCJlYCbQ380
there is only sound. The "Audio only" option is disabled.

_RPi3, LibreELEC 8.2.5, YT 6.2.2_

Kodi.log
```
18:37:32.953 T:1304425376  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.2) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'FCJlYCbQ380'}
18:37:34.446 T:1944957040  NOTICE: VideoPlayer: Opening: http://127.0.0.1:50152/FCJlYCbQ380.mpd
18:37:34.446 T:1944957040 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:37:34.447 T:1429205920  NOTICE: Creating InputStream
18:37:34.605 T:1429205920  NOTICE: Creating Demuxer
18:37:34.605 T:1429205920  NOTICE: Opening stream: 1 source: 256
18:37:34.885 T:1429205920  NOTICE: Finding audio codec for: 86018
18:37:34.887 T:1429205920  NOTICE: Creating audio thread
18:37:34.888 T:1323824032  NOTICE: running thread: CVideoPlayerAudio::Process()
18:37:34.932 T:1429205920  NOTICE: Opening stream: 1 source: 256
18:37:34.933 T:1429205920  NOTICE: Finding audio codec for: 86018
18:37:34.941 T:1323824032  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
18:37:35.059 T:1429205920 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
18:37:44.648 T:1944957040  NOTICE: CVideoPlayer::CloseFile()
18:37:44.648 T:1944957040  NOTICE: VideoPlayer: waiting for threads to exit
18:37:44.654 T:1429205920  NOTICE: CVideoPlayer::OnExit()
18:37:44.654 T:1429205920  NOTICE: Closing stream player 1
18:37:44.717 T:1304425376   ERROR: AddOnLog: InputStream Adaptive: Download https://r3---sn-f5f7ln7l.googlevideo.com/videoplayback?fvip=4&expire=1542325053&initcwndbps=1213750&ipbits=0&sparams=clen,dur,ei,gir,id,initcwndbps,ip,ipbits,itag,keepalive,lmt,mime,mm,mn,ms,mv,pl,requiressl,source,expire&mime=audio/mp4&source=youtube&dur=491.218&id=o-ADoV-fk7aNktbi7rZlVVQtlxZH-ON1ByZJ7rk0-uEBKM&lmt=1542298885108759&itag=140&requiressl=yes&ip=89.67.188.209&keepalive=yes&signature=397D1C38ED2093437F51F820F65DDD9E17E12D4B.DEE74F004375F29B229753451B03A2621667407E&clen=7950598&mt=1542303266&pl=13&mv=m&ei=3a7tW4vSKYfOVOaNhIgC&ms=au,onr&mm=31,26&mn=sn-f5f7ln7l,sn-4g5e6nze&key=yt6&c=WEB_EMBEDDED_PLAYER&txp=2311222&gir=yes&beids=23758620 doesn't provide any data: invalid
18:37:44.719 T:1429205920  NOTICE: Waiting for audio thread to exit
18:37:44.740 T:1323824032  NOTICE: thread end: CVideoPlayerAudio::OnExit()
18:37:44.740 T:1429205920  NOTICE: Closing audio device
18:37:44.790 T:1429205920  NOTICE: Deleting audio codec
18:37:44.797 T:1944957040  NOTICE: VideoPlayer: finished waiting
18:37:44.807 T:1944957040  NOTICE: CVideoPlayer::CloseFile()
18:37:44.807 T:1944957040  NOTICE: VideoPlayer: waiting for threads to exit
18:37:44.807 T:1944957040  NOTICE: VideoPlayer: finished waiting
18:37:44.808 T:1944957040  NOTICE: CVideoPlayer::CloseFile()
18:37:44.808 T:1944957040  NOTICE: VideoPlayer: waiting for threads to exit
18:37:44.808 T:1944957040  NOTICE: VideoPlayer: finished waiting
18:37:45.974 T:1135604640  NOTICE: [plugin.video.youtube] Running: YouTube (6.2.2) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /events/post_play/
                                            	Params: {'video_id': 'FCJlYCbQ380', 'refresh_only': 'true'}

```
I'm not sure what it was, but later the movie worked.

**Comment by anxdpanic** [comment] 2018-11-16 20:41
Should be resolved with https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.3-dev
The only video streams available that are >360p are unsupported mpeg-dash VP9 streams. Though it does look like VP9 w/ InputStream Adaptive might be on the horizon for K18.

**Comment by anxdpanic** [comment] 2018-11-16 20:44
Looks like the other qualities have now propagated which is why it started working

**Closed by anxdpanic** 2018-11-16 20:44 UTC

**Comment by XxAcielxX** [comment] 2018-12-14 11:19
Another video (https://youtu.be/56hSbNy9imI) is also giving similar behaviour. It's plays in Audio Only Mode when there is 720p quality available on YouTube.

RPi3, Milhouse Build of LE 9.0

**Comment by anxdpanic** [comment] 2018-12-14 12:58
@XxAcielxX  
I wasn't able to reproduce, but a stream using the AV1 codec(not supported currently) was included in the generated dash which may have caused the issue. AV1 streams will be discard now with current master/6.2.x branch.
