### ISSUE TITLE
Failing videos

### ISSUE THREAD

**Issue by jonisb** [jdf76/plugin.video.youtube#610] opened 2019-06-01 18:07 UTC
Using Kodi 18.2 64bit on Windows 10 Pro

Some new videos from my usual channels don't work via the plugin, trying older video from same channel still work so appears something changed with the new videos. The videos fail with no error message or might even crash Kodi.

Here are two example videos that fail for me, disabling mped-dash they work.
https://www.youtube.com/watch?v=-yJmDPK8-rM
https://www.youtube.com/watch?v=tdLlPOqHNKE

Here is a log for both videos failing:
[log](https://paste.kodi.tv/vuvetuwatu.kodi)

**Comment by anxdpanic** [comment] 2019-06-01 18:49
Thanks for reporting, it appears this only affects v2.3.19 of InputStream Adaptive. https://github.com/peak3d/inputstream.adaptive/issues/275

As a temporary work around, you could enable `Always ask for quality` in the YouTube add-on, if the mpeg-dash quality reads `DASH (mpd)` then choose the non-dash stream/720p

**Comment by jonisb** [comment] 2019-06-01 19:01
Thanks for the quick reply :-)

Is there a way to downgrade InputStream Adaptive until there is an update?

**Comment by anxdpanic** [comment] 2019-06-05 15:34
I've worked around the issue in the YouTube add-on

If you'd like to test, you can find the 6.5.0 alpha zips in the [Installation - In-development](https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions) section on the wiki


With the latest test version, quality selection has also been added, see; `YouTube add-on Settings` - `MPEG-DASH` - `Video quality`

**Comment by jonisb** [comment] 2019-06-05 18:09
Great work, both videos work on my test system.

**Comment by jonisb** [comment] 2019-06-06 16:32
Sorry to reopen this, but I'm having some more problems with mpeg-dash.

This video either has a spinning busy symbol (on my test system) or the audio plays but no video (on my main system)
https://www.youtube.com/watch?v=EFIESZkxm-c

Don't know if it is related to the original problem.

Log [part1](https://paste.kodi.tv/owomixigam.kodi) and [part2](https://paste.kodi.tv/raholekefa.kodi)

**Comment by anxdpanic** [comment] 2019-06-06 17:32
Thanks for the report, appears to be a different issue.
Should be resolved with #613 
Going to give some time for other issues before pushing a new alpha/beta.

**Comment by jonisb** [comment] 2019-06-06 17:48
Cool, do you want more video examples? I think I have see this problem with a couple of more videos.

**Comment by anxdpanic** [comment] 2019-06-06 17:51
Please do. Don't worry about logs for that, if I can't reproduce the issue I will ask if you have time. 👍

**Comment by anxdpanic** [comment] 2019-06-06 21:25
I bumped to alpha2 since I made some additional changes, [Installation - In-development](https://github.com/jdf76/plugin.video.youtube/wiki/Installation#in-development-versions)

**Comment by jonisb** [comment] 2019-06-06 23:07
So the other videos worked on my test system even thou they didn't work on my HTPC, so I did not find any other videos to test.

So with alpha 2 my last problematic video worked again so nice work, I'll test some more tomorrow.

I really appreciate to swiftness :astonished:

**Comment by anxdpanic** [comment] 2019-06-07 22:12
Issue is also resolved with InputStream Adaptive v2.3.21

**Closed by anxdpanic** 2019-06-07 22:12 UTC

**Comment by jonisb** [comment] 2019-06-07 22:32
Cool, all problematic videos work on both of my systems so I'm happy 😄 thanks.
