### ISSUE TITLE
Stop video get search window

### ISSUE THREAD

**Issue by lienjul** [jdf76/plugin.video.youtube#712] opened 2019-12-28 10:06 UTC
On YouTube 6.5.2 when i'm accelerating the video and stop it a search window pops up there is a cancel button when press it it's still searching.
Other information i'm using the latest LibreELEC 9.2.0 on Raspberry Pi 3.
I've recorded a video, you can find it here :
https://framadrop.org/r/5oMe3t2lWO#aGO1sHxNRGzMBZ9walC/rvW9jBuYRv0cUqks7YDxZA4=

Here's some pictures :
Stop the video
![Capture d’écran_2019-12-28_12-00-56](https://user-images.githubusercontent.com/59307322/71542714-ec3dcf00-2969-11ea-9ceb-c09b4c4fc320.png)
The search pop up wich appears after stop the video
![Capture d’écran_2019-12-28_12-01-11](https://user-images.githubusercontent.com/59307322/71542717-f3fd7380-2969-11ea-8048-d52045fc624c.png)
The circle turning around, I've to go backword in order to quit the application
![Capture d’écran_2019-12-28_12-01-26](https://user-images.githubusercontent.com/59307322/71542718-0081cc00-296a-11ea-8d24-13ed4fd9cd03.png)
I've to open the YouTube application and search for new video again, the last search is lost.
I'm using this YouTube application for years, I've never seen this behaviour before.

**Comment by lienjul** [comment] 2019-12-31 17:54
I can reproduce this behaviour on LibreELEC 9.2.0 only.
I've downgraded LibreELEC in 9.0 version, the message does not appears in 9.0.

**Comment by drrak** [comment] 2020-01-06 12:39
Translator:
I have a similar problem. After watching the searched movie, the search engine appears instead of the list of searched movies.

_RPi3, Kodu 18.5, YT 6.5.2_

**Comment by anxdpanic** [comment] 2020-01-23 20:04
I will try to add a toggle for this behavior, with the fix for this as the default.

The issue is the fix for this issue makes the Search menu unusable from remotes.

**Comment by anxdpanic** [comment] 2020-01-24 22:05
This is fixed by #721

**Comment by anxdpanic** [comment] 2020-01-25 19:57
The testing repositories have 6.5.3~beta1 with the fix added, zip is also found https://github.com/jdf76/plugin.video.youtube/releases/tag/6.5.3-dev

**Closed by anxdpanic** 2020-01-25 19:57 UTC
