### ISSUE TITLE
Developer provided API-Keys

### ISSUE THREAD

**Issue by Lunatixz** [jdf76/plugin.video.youtube#184] opened 2017-10-30 02:26 UTC
Hello, I'm interested in adding a new "API-Key" feature to the youtube plugin you're currently maintaining. I'd like to know if you are interested and would like to discuss implementation?

I propose adding a method that will allow developers to temporarily insert his/her api key in order to relieve default key burden. 

I'm leaning toward using : https://github.com/ruuk/script.module.addon.signals , However we can also use window properties.

Let me know what you think.

**Comment by anxdpanic** [comment] 2017-10-30 13:23
Would be a great addition. 

I think addon.signals would be the way to go, it doesn't appear to log any details so whole keys can still remain out of the log.

I think a signal here to overwrite main['key'] would be the easiest way to achieve it. https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_plugin/youtube/client/login_client.py#L30

I'll pm you my email on the forum, let me know if you have any questions.

**Comment by Lunatixz** [comment] 2017-10-30 14:42
@anxdpanic I emailed you... Email name is Kevin :)

**Comment by Lunatixz** [comment] 2017-11-02 16:37
I'm not sure if I can use addonsignals. Its registration system requires per plugin authorization. If I can't find an alternative I might end up using window properties.

**Comment by anxdpanic** [comment] 2017-11-02 18:04
Sounds good. Not sure if it's really a concern but with window properties the developers key is exposed to other add-ons. If you think that's a concern maybe sharing the add-on id via window property to register the signal?

**Comment by Lunatixz** [comment] 2017-11-02 20:20
It can certainly be done.... I'm not too worried about security since the keys have to be stored via the originating plugin anyway. If someone wants access to the keys, addonsignals won't stop them.

**Comment by anxdpanic** [comment] 2017-11-02 21:51
I don't think the youtube-tv keys should be exposed, those are used only for listing my subscriptions and don't have the quota issue(different api).

Can the window property be cleared after configured? https://github.com/Lunatixz/plugin.video.youtube/blob/Developer_Keys/resources/lib/youtube_plugin/youtube/client/login_client.py#L36-L37 Another add-on could render the add-on unusable(until restart) if its not properly coded to clear.

https://github.com/Lunatixz/plugin.video.youtube/blob/Developer_Keys/resources/lib/youtube_plugin/youtube/client/login_client.py#L34 context.log_notice() for print

Just a mention is the logged in context won't be available to those keys, iirc the api allows api key to be changed and keep the logged context from the add-ons id/secret. I removed it in add-on and force log out on key changes because of the TOS and limit evasion, not sure the same would apply here though.

**Comment by Lunatixz** [comment] 2017-11-02 21:56
I'll remove youtube-tv.

Yes you can clear properties... one of the reasons I ended up using a window property.
https://github.com/Lunatixz/screensaver.system47/blob/master/default.py#L80

Is LoginClient called on every plugin instance, or only on initial Kodi boot?

**Comment by anxdpanic** [comment] 2017-11-02 22:02
Sorry, I meant specifically can we clear it in the YouTube add-on to avoid any adverse affects being caused by another add-on.

LoginClient is called every instance.

**Comment by Lunatixz** [comment] 2017-11-02 22:11
Yes, I'll refactor to allow self clearing...

**Comment by anxdpanic** [comment] 2017-11-13 18:38
How's this looking? I can add it here if time is an issue, with screensaver.system47 I'll be able to test easily.

**Comment by Lunatixz** [comment] 2017-11-13 18:44
Sorry, I was caught up with other projects... trying to refresh my last thoughts on this. I believe I was looking for a solution to clear the property... Any ideas to where we can add that?

**Comment by anxdpanic** [comment] 2017-11-13 18:51
No worries, just wanted to check on it before packing the next alpha zips. 
Should be able to clear the property after setting self._config in the init of login_client.LoginClient

**Comment by Lunatixz** [comment] 2017-11-13 19:08
Sounds good.... Yeah you can test with system47 :) THX

**Comment by Lunatixz** [comment] 2017-11-13 19:09
Also food for thought add a user settings to disable developer keys from being used.

**Comment by anxdpanic** [comment] 2017-11-13 23:51
I have it all added, including the setting. Without a large refactor not able to use client id or secret as it causes refresh token issues. So at this point it's just using the api key. 

Similar issue with post play events and suggest videos being added, without a large refactor I don't see a way to safely allow the key to be reused for those, and likely not the developers intent so I've added a couple parameters to the plugin play url, &suggested=false will make sure suggested videos aren't added to playlist, and &incognito=true will skip post play (watch list/history). They are backwards safe so old versions won't have any issues.

The other option to avoid any additional add-on interference would be to use the youtube add-on as a module and import youtube_resolver (will use the dev key) and use youtube_resolver.resolve() to get the resolved streams to handle directly.

Should have the zips up earlier tomorrow

**Comment by Lunatixz** [comment] 2017-11-14 00:33
What token refresh issue? I didn't notice anything abnormal. I could have missed something... During my tests I was able to have youtube use my keys for playback, then a clear would restore original settings on next play. I needed to move the clearproperty closer to the plugins functions so that it would clear sooner.

**Comment by anxdpanic** [comment] 2017-11-14 12:53
The token refresh issue occurs when the refreshing tokens come due (~1hr). If say system47 runs, user does something other than youtube add-on and after an hour system47 starts again, the refresh and system47 will fail since the client id and secret are unauthorized for the refresh. 

api key only has it's benefits, instead of external add-on always using a logged out context it will be either logged in or out depending on the status of the youtube add-on. 

At some point the intention is to do a larger refactor and moving api to it's own module, which should improve the situation overall.

**Comment by Lunatixz** [comment] 2017-11-14 14:17
Wouldn't refresh token build off the CONIFGS? if not... This was the wrong place to insert developer keys; they would need to be move closer to its initial call.

**Comment by anxdpanic** [comment] 2017-11-14 14:35
Yea, the login parts of the add-on need a refactor beyond this change. Though with fresh eyes today, it could be done after the add-ons tokens are handled or bypass that altogether allowing client id and secret. Is this favorable to you? There is no way in the current login set up to allow add-ons to be logged in this way.

**Comment by anxdpanic** [comment] 2017-11-14 15:24
all fixed up, client id and secret are optional and if provided will bypass login handling(always logged out).

**Comment by Lunatixz** [comment] 2017-11-14 15:34
What's the minimum level of API required to avoid the limits met prompt?

**Comment by anxdpanic** [comment] 2017-11-14 15:37
Not sure what you're asking exactly

**Comment by Lunatixz** [comment] 2017-11-14 16:48
Correct the idea is not to evade but facilitate using a developers api... okay so the I'm providing the min. level of API needed... I'll review your modifications.

**Comment by anxdpanic** [comment] 2017-11-14 16:54
Yea, if you look in the google dev console you should see the activity on your api key from my testing.

**Comment by Lunatixz** [comment] 2017-11-14 18:01
I had to update keys... update pushed to my repo.

**Comment by anxdpanic** [comment] 2017-11-14 19:03
Working good here with the updated keys. 
You may also want to change:
https://github.com/Lunatixz/screensaver.system47/blob/master/default.py#L35
to 'plugin://plugin.video.youtube/play/?video_id=Y_4iAWobejY&suggested=false&incognito=true'
will ensure the addon don't create a playlist if the user has suggested videos enabled, and not add to user history. Shouldn't cause any issues with older versions of youtube add-on either.

**Comment by Lunatixz** [comment] 2017-11-14 19:05
Thanks.. good idea.

**Comment by anxdpanic** [comment] 2018-01-20 15:51
Closing now, at release version. 
https://github.com/jdf76/plugin.video.youtube/releases

**Closed by anxdpanic** 2018-01-20 15:51 UTC

**Comment by anxdpanic** [comment] 2018-02-10 14:44
@Lunatixz 
I've made some improvements to this, I've marked the window property updates as deprecated, will remove it in a future version.

https://github.com/jdf76/plugin.video.youtube/blob/master/resources/lib/youtube_registration.py
Improvements are: keys stored b64encoded, clears cache between developer key changes to ensure correct content is shown, keys usage is passed on to all following calls(channel addons), not relying on window properties. 

I tested the new method using system47 and Cheddar using my own test set of keys. It looks like your keys in system47 have an error that doesn't present itself with /play/ but does if you use it for /channel/ like in Cheddar. Which makes sense, on the /play/ route only post play and suggested videos would have api usage, overlooked this because access tokens are used if present but there is no sign-on for developer keys.

Also with system47 on my test system this whole time I noticed that 'Always ask for quality' would happen when the screensaver was activated. I've simplified the parameters for screensaver usage, instead of suggested=false&incognito=true you can simply use screensaver=true and this will also ignore 'Always ask for quality'
