### ISSUE TITLE
Live streams through channel/live are playing only for five seconds

### ISSUE THREAD

**Issue by Twilight0** [jdf76/plugin.video.youtube#559] opened 2019-01-29 13:40 UTC
For instance Progressive Astronaut:

https://www.youtube.com/channel/UCE2IKH8vYeRHLgaxFu0Paxw/live

After some research it appears that this issue is present on older Krypton release.

**Comment by anxdpanic** [comment] 2019-04-09 16:12
Duplicate of #299

**Closed by anxdpanic** 2019-04-09 16:12 UTC
Labels: duplicate
