### ISSUE TITLE
My channel videos does not work (kodi.log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#656] opened 2019-08-16 16:27 UTC
```
18:19:05.694 T:1911550880  NOTICE: CAESinkPi:AddPackets Underrun (delay:0.00 frames:2205)
18:19:08.408 T:1742070688   ERROR: GetDirectory - Error getting
18:19:09.792 T:1496310688   ERROR: Previous line repeats 6 times.
18:19:09.793 T:1496310688  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /channel/UCQarM1M3_4G92Gph5v4BCEQ/
                                            	Params: {}
18:19:15.160 T:1496310688  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'DofsItASMks'}
18:19:17.449 T:1945292800  NOTICE: VideoPlayer: Opening: http://127.0.0.1:50152/DofsItASMks.mpd
18:19:17.449 T:1945292800 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:19:17.450 T:1445794720  NOTICE: Creating InputStream
18:19:17.614 T:1445794720  NOTICE: Creating Demuxer
18:19:17.615 T:1445794720  NOTICE: Opening stream: 1 source: 256
18:19:17.884 T:1445794720   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
18:19:17.884 T:1445794720   ERROR: CCurlFile::Open failed with code 403 for https://r4---sn-f5f7lnel.c.youtube.com/videoplayback?expire=1565993956&ei=hNdWXYLcDcfU7gTx26DADw&ip=89.64.63.15&cp=U0pVSllUUV9KUENQNV9RTlVKOnNPMzVKXy1QWUotbkNaZTRVX3JybmViS1NXZXVkMFNtZWNKTmt5R0s3aEI&id=o-AO6Diu8vSUbFpY1Xa2gCYm9wMazGgwLv-aFyKNULT9iy&itag=137&aitags=133,134,135,136,137,160,242,243,244,247,248,278&source=youtube&requiressl=yes&mm=30,26&mn=sn-f5f7lnel,sn-4g5edne6&ms=nxu,onr&mv=m&mvi=3&pl=15&sc=yes&initcwndbps=1638750&mime=video/mp4&gir=yes&clen=182043654&otfp=1&dur=481.566&lmt=1565969865655710&mt=1565972248&fvip=4&keepalive=yes&c=WEB&txp=2216222&sparams=expire,ei,ip,cp,id,aitags,source,requiressl,mime,gir,clen,otfp,dur,lmt&sig=ALgxI2wwRgIhAJ2z9qe8tgNZbiYGROnb7yluBDvCZjj7j4SNpsONjv1WAiEAqBV7PRVYYIQy_4DNCPPRA90OOPQedXHXQ7QdVyUd7I4=&lsparams=mm,mn,ms,mv,mvi,pl,sc,initcwndbps&lsig=AHylml4wRQIgISUq33LU4PpSc-n29poLlXozJlC5cz2SbMpRpwxf-foCIQDN6wr0KTxEgcKRvmD1wZjEdTyfXIHz_8niwJMI8N6RiQ==|Range=bytes%3d742-1865&seekable=0
18:19:17.884 T:1445794720   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
18:19:17.884 T:1445794720   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
18:19:17.885 T:1445794720  NOTICE: Creating video codec with codec id: 28
18:19:17.894 T:1445794720  NOTICE: Creating video thread
18:19:17.894 T:1445794720  NOTICE: Opening stream: 2 source: 256
18:19:17.894 T:1437406112  NOTICE: running thread: video_thread
18:19:18.015 T:1445794720   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
18:19:18.015 T:1445794720   ERROR: CCurlFile::Open failed with code 403 for https://r4---sn-f5f7lnel.c.youtube.com/videoplayback?expire=1565993956&ei=hNdWXYLcDcfU7gTx26DADw&ip=89.64.63.15&cp=U0pVSllUUV9KUENQNV9RTlVKOnNPMzVKXy1QWUotbkNaZTRVX3JybmViS1NXZXVkMFNtZWNKTmt5R0s3aEI&id=o-AO6Diu8vSUbFpY1Xa2gCYm9wMazGgwLv-aFyKNULT9iy&itag=140&source=youtube&requiressl=yes&mm=30,26&mn=sn-f5f7lnel,sn-4g5edne6&ms=nxu,onr&mv=m&mvi=3&pl=15&sc=yes&initcwndbps=1638750&mime=audio/mp4&gir=yes&clen=7801387&otfp=1&dur=481.976&lmt=1565969853337026&mt=1565972248&fvip=4&keepalive=yes&c=WEB&txp=2211222&sparams=expire,ei,ip,cp,id,itag,source,requiressl,mime,gir,clen,otfp,dur,lmt&sig=ALgxI2wwRQIgWBVrZmzW5UAGuhP9cBRxRmJyMpnjM1UGokx97anUVWMCIQD8X75p5k1Ce9rNitGqtb8qkbesys47Am92aUNPUChEKg==&lsparams=mm,mn,ms,mv,mvi,pl,sc,initcwndbps&lsig=AHylml4wRQIgISUq33LU4PpSc-n29poLlXozJlC5cz2SbMpRpwxf-foCIQDN6wr0KTxEgcKRvmD1wZjEdTyfXIHz_8niwJMI8N6RiQ==|Range=bytes%3d632-1251&seekable=0
18:19:18.015 T:1445794720   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
18:19:18.015 T:1445794720   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
18:19:18.015 T:1445794720  NOTICE: Finding audio codec for: 86018
18:19:18.020 T:1445794720  NOTICE: Creating audio thread
18:19:18.020 T:1427968928  NOTICE: running thread: CVideoPlayerAudio::Process()
18:19:18.021 T:1445794720  NOTICE: CVideoPlayer::OnExit()
18:19:18.021 T:1445794720  NOTICE: VideoPlayer: eof, waiting for queues to empty
18:19:18.021 T:1445794720  NOTICE: Closing stream player 1
18:19:18.021 T:1445794720  NOTICE: Waiting for audio thread to exit
18:19:18.033 T:1427968928  NOTICE: thread end: CVideoPlayerAudio::OnExit()
18:19:18.033 T:1445794720  NOTICE: Closing audio device
18:19:18.033 T:1445794720  NOTICE: Deleting audio codec
18:19:18.034 T:1445794720  NOTICE: Closing stream player 2
18:19:18.034 T:1437406112   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
18:19:18.034 T:1437406112  NOTICE: thread end: video_thread
18:19:18.034 T:1445794720  NOTICE: waiting for video thread to exit
18:19:18.034 T:1445794720  NOTICE: deleting video codec
18:19:18.065 T:1945292800  NOTICE: CVideoPlayer::CloseFile()
18:19:18.065 T:1945292800  NOTICE: VideoPlayer: waiting for threads to exit
18:19:18.065 T:1945292800  NOTICE: VideoPlayer: finished waiting
18:19:18.065 T:1945292800  NOTICE: CVideoPlayer::CloseFile()
18:19:18.065 T:1945292800  NOTICE: VideoPlayer: waiting for threads to exit
18:19:18.065 T:1945292800  NOTICE: VideoPlayer: finished waiting
```
_RPi3, LibrELEC 8.5.2, Kodi 17.6,  YouTube 6.5.1_

**Comment by drrak** [comment] 2019-08-18 15:47
and crash log:
```17:34:00.413 T:1403540384 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
17:39:19.998 T:1206903712 WARNING: Previous line repeats 1 times.
17:39:19.998 T:1206903712  NOTICE: metahandler: No SQLite rows requiring update
17:41:24.401 T:1945042944  NOTICE: CVideoPlayer::CloseFile()
17:41:24.401 T:1945042944  NOTICE: VideoPlayer: waiting for threads to exit
17:41:24.401 T:1257235360  NOTICE: CVideoPlayer::OnExit()
17:41:24.401 T:1257235360  NOTICE: Closing stream player 1
17:41:24.402 T:1257235360  NOTICE: Waiting for audio thread to exit
17:41:24.424 T:1380971424  NOTICE: thread end: CVideoPlayerAudio::OnExit()
17:41:24.424 T:1257235360  NOTICE: Closing audio device
17:41:24.476 T:1257235360  NOTICE: Deleting audio codec
17:41:24.476 T:1257235360  NOTICE: Closing stream player 2
17:41:24.476 T:1257235360  NOTICE: waiting for video thread to exit
17:41:24.501 T:1403540384  NOTICE: thread end: video_thread
17:41:24.502 T:1257235360  NOTICE: deleting video codec
17:41:24.514 T:1945042944  NOTICE: VideoPlayer: finished waiting
17:41:24.593 T:1945042944   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
17:41:24.931 T:1945042944  NOTICE: CVideoPlayer::CloseFile()
17:41:24.931 T:1945042944  NOTICE: VideoPlayer: waiting for threads to exit
17:41:24.931 T:1945042944  NOTICE: VideoPlayer: finished waiting
17:41:24.931 T:1945042944  NOTICE: CVideoPlayer::CloseFile()
17:41:24.931 T:1945042944  NOTICE: VideoPlayer: waiting for threads to exit
17:41:24.931 T:1945042944  NOTICE: VideoPlayer: finished waiting
17:41:30.669 T:1945042944   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
17:41:32.560 T:1097851808  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /
                                            	Params: {}
17:41:35.732 T:1097851808  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /special/new_uploaded_videos_tv/
                                            	Params: {}
17:41:43.639 T:1945042944   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
17:41:44.274 T:1362097056  NOTICE: metahandler: Initializing MetaHandlers version: 3.0.3
17:41:44.339 T:1362097056  NOTICE: metahandler: Loading sqlite3 as DB engine version: 3.15.2
17:41:44.346 T:1362097056  NOTICE: metahandler: No SQLite rows requiring update
17:42:19.738 T:1945042944   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
17:42:21.079 T:1362097056  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /channel/UCQarM1M3_4G92Gph5v4BCEQ/
                                            	Params: {}
17:42:32.045 T:1362097056  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.1) on Krypton (Kodi-17.6) with Python 2.7.13
                                            	Path: /play/
                                            	Params: {'video_id': 'otCftoOS1r4'}
17:42:33.791 T:1945042944  NOTICE: VideoPlayer: Opening: http://127.0.0.1:50152/otCftoOS1r4.mpd
17:42:33.791 T:1945042944 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:42:33.792 T:1413473184  NOTICE: Creating InputStream
17:42:33.971 T:1413473184  NOTICE: Creating Demuxer
17:42:33.971 T:1413473184  NOTICE: Opening stream: 1 source: 256
17:42:34.198 T:1413473184   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:42:34.198 T:1413473184   ERROR: CCurlFile::Open failed with code 403 for https://r5---sn-f5f7lnee.c.youtube.com/videoplayback?expire=1566164553&ei=6XFZXfbUA43u7QTakYPYBA&ip=89.64.63.15&cp=U0pVS1FRUl9KTUNQNV9JS1ZGOmIxMHJ5N3FUOTFYMkJDajhuT2xmcTdqSlhhSnhlNUVFUGV3WnU1V3d1OHQ&id=o-AKIHtpjjHh7uDvLVKBF1v_WWaXFW6bi19ve60YE9LjLE&itag=137&aitags=133,134,135,136,137,160,242,243,244,247,248,278&source=youtube&requiressl=yes&mm=30,26&mn=sn-f5f7lnee,sn-4g5ednld&ms=nxu,onr&mv=m&mvi=4&pl=15&sc=yes&initcwndbps=1788750&mime=video/mp4&gir=yes&clen=41001975&otfp=1&dur=1319.117&lmt=1552226421828479&mt=1566142887&fvip=5&keepalive=yes&c=WEB&txp=2216222&sparams=expire,ei,ip,cp,id,aitags,source,requiressl,mime,gir,clen,otfp,dur,lmt&sig=ALgxI2wwRgIhAJZM_WPBlsRdOopsuZrjKgIAGCkyPOhFbhfAxGXItnhoAiEAkfcLzHGbfqxPzOhorY9JLbfwWJ3kiJ2LDOhI5v2jRBs=&lsparams=mm,mn,ms,mv,mvi,pl,sc,initcwndbps&lsig=AHylml4wRgIhAJbDews6LlyLIjOmXh9CEJ6yWrwitSeA90u72412mLcZAiEAi5UBkasNYvIdbyltmtA3X9ZEI_CuTNHpmw6PRunASBA=|Range=bytes%3d765-3760&seekable=0
17:42:34.198 T:1413473184   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
17:42:34.198 T:1413473184   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
17:42:34.199 T:1413473184  NOTICE: Creating video codec with codec id: 28
17:42:34.207 T:1413473184  NOTICE: Creating video thread
17:42:34.207 T:1413473184  NOTICE: Opening stream: 2 source: 256
17:42:34.207 T:1403847584  NOTICE: running thread: video_thread
17:42:34.318 T:1413473184   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
17:42:34.319 T:1413473184   ERROR: CCurlFile::Open failed with code 403 for https://r5---sn-f5f7lnee.c.youtube.com/videoplayback?expire=1566164553&ei=6XFZXfbUA43u7QTakYPYBA&ip=89.64.63.15&cp=U0pVS1FRUl9KTUNQNV9JS1ZGOmIxMHJ5N3FUOTFYMkJDajhuT2xmcTdqSlhhSnhlNUVFUGV3WnU1V3d1OHQ&id=o-AKIHtpjjHh7uDvLVKBF1v_WWaXFW6bi19ve60YE9LjLE&itag=140&source=youtube&requiressl=yes&mm=30,26&mn=sn-f5f7lnee,sn-4g5ednld&ms=nxu,onr&mv=m&mvi=4&pl=15&sc=yes&initcwndbps=1788750&mime=audio/mp4&gir=yes&clen=21350117&otfp=1&dur=1319.171&lmt=1552226405840907&mt=1566142887&fvip=5&keepalive=yes&c=WEB&txp=2211222&sparams=expire,ei,ip,cp,id,itag,source,requiressl,mime,gir,clen,otfp,dur,lmt&sig=ALgxI2wwRgIhAIoGzxK0eyMkCiCLKEn2WB1fLlj9ABvPZWfNZcHtNRBvAiEAtr_dBtDJnmfNBkjUFhz0ZqS0mOFecjQxBeCkGqFdmzo=&lsparams=mm,mn,ms,mv,mvi,pl,sc,initcwndbps&lsig=AHylml4wRgIhAJbDews6LlyLIjOmXh9CEJ6yWrwitSeA90u72412mLcZAiEAi5UBkasNYvIdbyltmtA3X9ZEI_CuTNHpmw6PRunASBA=|Range=bytes%3d656-2283&seekable=0
17:42:34.319 T:1413473184   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
17:42:34.319 T:1413473184   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
17:42:34.319 T:1413473184  NOTICE: Finding audio codec for: 86018
17:42:34.323 T:1413473184  NOTICE: Creating audio thread
17:42:34.323 T:1380971424  NOTICE: running thread: CVideoPlayerAudio::Process()
17:42:34.324 T:1413473184  NOTICE: CVideoPlayer::OnExit()
17:42:34.324 T:1413473184  NOTICE: VideoPlayer: eof, waiting for queues to empty
17:42:34.324 T:1413473184  NOTICE: Closing stream player 1
17:42:34.324 T:1413473184  NOTICE: Waiting for audio thread to exit
17:42:34.333 T:1380971424  NOTICE: thread end: CVideoPlayerAudio::OnExit()
17:42:34.333 T:1413473184  NOTICE: Closing audio device
17:42:34.333 T:1413473184  NOTICE: Deleting audio codec
17:42:34.333 T:1413473184  NOTICE: Closing stream player 2
17:42:34.334 T:1413473184  NOTICE: waiting for video thread to exit
17:42:34.334 T:1403847584   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
17:42:34.334 T:1403847584  NOTICE: thread end: video_thread
17:42:34.334 T:1413473184  NOTICE: deleting video codec
```

**Comment by anxdpanic** [comment] 2019-08-23 01:08
I haven't been able to reproduce, and you've been the only report. Will need a complete log with debugging enabled to hopefully catch the issue.

**Comment by drrak** [comment] 2019-08-23 07:11
https://drive.google.com/open?id=1BXi_dawdpF2P7iWmABpauT4LSNVrv5ln
This is useful?

**Comment by drrak** [comment] 2019-09-06 14:44
You already know how to fix it?
Btw. Play audio only works.

**Comment by drrak** [comment] 2019-09-07 09:33
Something is wrong. "My Channel" video works if i disable "InputStream Adaptive" for video. Which is not cool, because this is only 720p :(

**Comment by anxdpanic** [comment] 2019-09-11 17:11
@drrak sorry for the long delay, your log is no longer available, and is required. I can use mpeg-dash for my channel videos without issue, and no new reports since opening, so I don't have enough information on the issue.

**Comment by drrak** [comment] 2019-09-11 17:20
https://drive.google.com/open?id=1HWxj_SaKhxh9ukQfTyLBso4iT5NruIiT
I hope this log is enough.

**Comment by anxdpanic** [comment] 2019-09-11 18:51
It's an issue I can't fix, it works with Kodi 18 and 19, and not on 17.x. If you experience an issue with 18 or 19, open a new issue with a clean debug log please.

I'm going to close this issue, but I've opened a new 'can't fix' issue to track this.

**Closed by anxdpanic** 2019-09-11 18:51 UTC
