### ISSUE TITLE
Unable to play some videos since 3 days ago

### ISSUE THREAD

**Issue by FSynchro** [jdf76/plugin.video.youtube#285] opened 2018-02-14 16:17 UTC
Hello.

Whenever I try to play: https://www.youtube.com/watch?v=pwu4v7VV5Hc

it produces this error in kodi.log:
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.Exception'>
                                            Error Contents: Signature function not found
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 7, in <module>
                                                runner.run(__provider__)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 40, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 24, in run
                                                results = provider.navigate(context)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 87, in navigate
                                                result = method(context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 11, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 475, in on_play
                                                return yt_play.play_video(self, context, re_match)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 19, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 79, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 403, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 738, in _method_get_video_info
                                                parse_to_stream_list(url_encoded_fmt_stream_map)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 700, in parse_to_stream_list
                                                url += '&signature=%s' % cipher.get_signature(stream_map['s'])
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 24, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._java_script_url)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 101, in get
                                                cached_data = partial_func()
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 57, in _load_json_script
                                                return self._load_java_script(java_script)
                                              File "/home/pi/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 62, in _load_java_script
                                                raise Exception('Signature function not found')
                                            Exception: Signature function not found
                                            -->End of Python script error report<--

However this video works fine:

https://www.youtube.com/watch?v=QpDn4-Na5co

I have this problem with about 70% of the videos I try to play.

**Comment by Eonix** [comment] 2018-02-14 17:13
Just got the same exception when sending https://www.youtube.com/watch?v=7T1E1aI95Ro to kodi using Play to Kodi extension for chrome.

**Comment by anxdpanic** [comment] 2018-02-14 18:46
YouTube has changed something, this will mainly affect music videos but other videos will be affected as well.

**Comment by posti85** [comment] 2018-02-14 19:09
Yep,  same problem here. I have just found it out.

**Comment by pferreir** [comment] 2018-02-14 20:05
Same issue.

**Comment by aintnogeek** [comment] 2018-02-15 13:25
I even reinstalled all my RPI setup with OSMC, and Libreelec.... and as it looks I am not only one to have such issue, that this plugin is not system.... still sad

**Comment by anxdpanic** [comment] 2018-02-15 20:14
should be resolved here: https://github.com/jdf76/plugin.video.youtube/releases/tag/6.0.0-dev

**Comment by jlopezinc** [comment] 2018-02-15 22:26
@anxdpanic: confirmed that 6.0.0.alpha6 solves the issue. Thanks

**Comment by zarianu** [comment] 2018-02-16 02:04
@anxdpanic thanks for your efforts! any plans to backport this fix in mainline release?

**Comment by prefmon** [comment] 2018-02-16 11:58
Great, 6.0.0.alpha6 solves the issue. Many thanks!!

**Comment by anxdpanic** [comment] 2018-02-17 16:10
The fix has been brought back to 5.5.x as a bugfix, so if you'd prefer to use a non-testing version the new version is here: https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.1

**Comment by ikus060** [comment] 2018-02-20 12:49
Just want to leave a big "Thank you" to the maintainer of this plugin.

**Comment by anxdpanic** [comment] 2018-02-22 14:34
5.4.8 and 5.5.1 is now on the Official repository and include the fix.

**Closed by anxdpanic** 2018-02-22 14:34 UTC

**Comment by martinmolema** [comment] 2018-05-20 08:31
plugin.video.youtube-6.0.0.beta10.zip fixed this for me

**Comment by GergelyNovak** [comment] 2018-09-08 09:36
The same error ("Signature function not found") is happening again on the latest versions (both on 6.1.3 and on 6.2.0-dev).

**Comment by syagev** [comment] 2018-09-08 14:11
@anxdpanic this indeed happens with latest version.. can you reopen please?

**Comment by anxdpanic** [comment] 2018-09-08 14:13
There is already a new issue open for this, see #424

**Comment by anxdpanic** [comment] 2018-09-08 14:46
Issue is fixed in [6.1.4](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.4) and [6.2.0-dev](https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.0-dev)
Also a thank you @Twilight0

**Comment by grazcata** [comment] 2018-09-23 16:51
thank you.

**Comment by teodoryantcheff** [comment] 2018-11-07 18:03
Seems to be back -- log https://bpaste.net/show/fddfc3b80800

**Comment by anxdpanic** [comment] 2018-11-07 18:47
https://github.com/jdf76/plugin.video.youtube/releases/tag/6.2.2

**Comment by teodoryantcheff** [comment] 2018-11-08 17:16
Confirmed, works. Thanks!

**Comment by gucker12** [comment] 2020-01-28 16:27
I know this has been a long time now since the last entry. But now with
version YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.17 i have the same problem:

Some vids are playing some don't. When trying to watch:
https://www.youtube.com/watch?v=bDnA_coA168
or: 
https://www.youtube.com/watch?v=l7BUi58z_YM
I get the error below:

but that one is working:
https://www.youtube.com/watch?v=IGYM1L-wynI.

020-01-28 16:58:59.764 T:139802578069248  NOTICE: [plugin.video.youtube] Running: YouTube (6.5.2) on Leia (Kodi-18.5) with Python 2.7.17
                                            	Path: /play/
                                            	Params: {'video_id': 'bDnA_coA168'}
2020-01-28 16:59:01.844 T:139802578069248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'splice'
                                            Traceback (most recent call last):
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 97, in navigate
                                                result = method(context, re_match)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 724, in on_play
                                                return yt_play.play_video(self, context)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_play.py", line 46, in play_video
                                                video_streams = client.get_video_streams(context, video_id)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/client/youtube.py", line 96, in get_video_streams
                                                video_streams = video_info.load_stream_infos(video_id, player_config, cookies)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 505, in load_stream_infos
                                                return self._method_get_video_info(video_id, player_config, cookies)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 1029, in _method_get_video_info
                                                parse_to_stream_list(std_fmts)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/video_info.py", line 991, in parse_to_stream_list
                                                url = ''.join([url, sig_param, cipher.get_signature(stream_map['s'])])
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 32, in get_signature
                                                json_script = function_cache.get(FunctionCache.ONE_DAY, self._load_json_script, self._javascript_url)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/function_cache.py", line 108, in get
                                                cached_data = partial_func()
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 55, in _load_json_script
                                                return self._load_javascript(javascript)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 98, in _load_javascript
                                                _function = self._get_object_function(object_name, function_name, javascript)
                                              File "/home/as/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/signature/cipher.py", line 199, in _get_object_function
                                                return self._object_cache[object_name][function_name]
                                            KeyError: u'splice'
                                            -->End of Python script error report<--

**Comment by anxdpanic** [comment] 2020-01-28 16:28
@gucker12 There is a pinned issue that, https://github.com/jdf76/plugin.video.youtube/issues/719
