### ISSUE TITLE
Sudden "invalid parameters" message

### ISSUE THREAD

**Issue by pitsi** [jdf76/plugin.video.youtube#226] opened 2018-01-09 10:50 UTC
So, I made my own api keys ~1 month ago so as to close issue #211 and I have been using them on all 3 of my devices that run plugin.video.youtube, either version 5.5.0-alpha14 (kodi 17.6) or 5.4.6-alpha14  (kodi 14.2).
And suddenly, today, I get a message saying "invalid parameters" and no video is playing on all 3! Searches work, they do return results, favorites that are not direct links to videos work too. What can I try other than removing my keys and/or making new ones or resetting the addon and configuring it again? 

This is what the log says when trying to play a video on kodi 17.6
```
09:34:44.586 T:140368369862400  NOTICE: [plugin.video.youtube] Running: YouTube (5.5.0~alpha14) on Krypton (Kodi-17.6) with Python 2.7.14+
09:35:18.098 T:140370459467904   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=5Gdlb5hCcwU]
09:37:19.970 T:140368346310400  NOTICE: [plugin.video.youtube] Running: YouTube (5.5.0~alpha14) on Krypton (Kodi-17.6) with Python 2.7.14+
09:37:21.441 T:140370459467904   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=04vIxVVRBcg]

11:47:01.648 T:1529861024  NOTICE: [plugin.video.youtube] Running: YouTube (5.5.0~alpha14) on Krypton (Kodi-17.6) with Python 2.7.13
11:47:07.100 T:1945108480   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=5Gdlb5hCcwU]
```

The top ones are from my pc (debian testing x64 and kodi 17.6) and the bottom ones are from the rpi zero (libreelec 8.2.2 and kodi 17.6), both with plugin.video.youtube 5.5.0-alpha14 as it mentions. I know they do not say much, so I will try pulling the logs from kodi 14.2 later on, in case they provide more info.

**Comment by pitsi** [comment] 2018-01-09 11:10
And this is what kodi 14.2 logs
```
13:06:56 T:2948594496  NOTICE: Thread LanguageInvoker start, auto delete: false
13:06:56 T:2948594496  NOTICE: -->Python Interpreter Initialized<--
13:06:57 T:2948594496  NOTICE: [plugin.video.youtube] Running: YouTube (5.4.6~alpha14) on Helix (Kodi-14.2) with Python 2.7.3
13:06:57 T:2948594496   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:334: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              SNIMissingWarning
13:06:57 T:2948594496   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
13:06:57 T:2948594496   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
13:06:58 T:2948594496   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:132: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecurePlatformWarning
13:06:58 T:2948594496   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connectionpool.py:843: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
                                              InsecureRequestWarning)
13:06:58 T:3046266624   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=5Gdlb5hCcwU]
13:06:58 T:2948594496  NOTICE: Thread BackgroundLoader start, auto delete: false

```

**Comment by greystashh** [comment] 2018-01-09 13:47
Inputstream doesnt work neither with 5.4.5

**Comment by anxdpanic** [comment] 2018-01-09 14:06
Thanks for the reports, I can reproduce and I'm taking a look as I can. Oddly parameters are the same between versions, which just adds to the issue.

**Comment by pitsi** [comment] 2018-01-09 14:49
@greystashh 
I would check about inputstream if I could play any video :p 

@anxdpanic 
Thank you for the quick responce. That "InsecurePlatformWarning" there however made me think of my email clients where I had to enable gmail's "Allow less secure apps" for them to work. Let's hope this stupidity was not brought to youtube as well...

**Comment by anxdpanic** [comment] 2018-01-09 14:57
@pitsi To silence that in the add-on Settings - Advanced - Force SSL certificate verification. It can cause issues on systems so you may not be able to enable it in all installations.

#227 fixes the issues, but mpeg-dash is no longer available. The way things look at the moment, the future of mpeg-dash support in the add-on may have come to an end. All 'el' parameters(that I'm aware of, its undocumented) and the website aren't returning the url required anymore. Hopefully this is temporary or another way is found.

**Comment by pitsi** [comment] 2018-01-09 15:05
It may sound dumb, but how does that setting (mpeg-dash) affect a system that has it disabled and does not use inputstream.adaptive at all (i.e on my kodi 14.2)?

I just disabled mpeg-dash on my desktop pc with kodi 17.6 and videos still fail to play. The same error pops up in the log as well
```
17:04:55.468 T:140603471951616  NOTICE: [plugin.video.youtube] Running: YouTube (5.5.0~alpha14) on Krypton (Kodi-17.6) with Python 2.7.14+
17:04:56.735 T:140605050802304   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.youtube/play/?video_id=5Gdlb5hCcwU]
```

**Comment by anxdpanic** [comment] 2018-01-09 15:10
The error isn't with dash, the error is fixed by the change in #227 . But dash is no longer available due to the change by youtube.

**Comment by jdf76** [comment] 2018-01-09 15:11
Did you download the update, mainly because he didn’t update the version string so it wont update happen unless you manually update it.

Jeff

**Comment by pitsi** [comment] 2018-01-09 15:15
Do you mean this? 
https://github.com/jdf76/plugin.video.youtube/commit/553cc456c4037039534421ffb38820c42df5b2f8

No, I just saw it. Give me a sec to edit my local files accordingly and I will report back.

**Comment by pix0wl** [comment] 2018-01-09 15:21
Deleting this line works for me. Thank you for fixing.

**Comment by pitsi** [comment] 2018-01-09 15:23
Yeap, removing that line makes the addon functional again. Thank you so much :)
Wish me luck now as I try to remove it using nano in a ~700 line file on the *elecs :P

**Comment by jdf76** [comment] 2018-01-09 15:23
Use vi ;)

Jeff

**Comment by anxdpanic** [comment] 2018-01-09 15:25
thanks for confirming :)

in nano just ctrl + w for 'def _method_get_video_info'
jump you to the right area

**Comment by pitsi** [comment] 2018-01-09 15:34
Also working on 5.4.6-alpha14 of kodi 14.2.

**Comment by anxdpanic** [comment] 2018-01-09 18:07
I've bumped the alpha zips. https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.0-alpha

**Closed by anxdpanic** 2018-01-09 18:07 UTC
