### ISSUE TITLE
Authorization resets on reboot

### ISSUE THREAD

**Issue by sprnza** [jdf76/plugin.video.youtube#66] opened 2017-06-05 09:39 UTC
Hi there!
I'm using KODI 17.3 on Ubuntu 14.04.5. And my issue is Youtube addon resets authorisation on system reboot. So I complete auth procedure with entering two 8 digit codes, I get Youtube addon added under my Google account and everything works just fine until I restart my PC. The youtube plugin dissapears under my Google account also.
What could be wrong here?

**Comment by dbalzan** [comment] 2017-08-24 19:32
I don't know if it helps but I have also experienced this issue when the plugin errors.  As a quick fix you can save the settings.xml file in the plugin's userdata directory when its working and then restore it when its not.

**Comment by anxdpanic** [comment] 2017-09-24 16:34
Not able to reproduce. If you can catch this and provide a debug log from before and after restart, I will take a look to see if there is any indication of what may be happening.

**Comment by anxdpanic** [comment] 2018-02-07 15:53
Closed by #276 

API keys and login tokens will be synced with json files, and can be restored on settings loss.

**Closed** 2018-02-07 15:53 UTC
