### ISSUE TITLE
Suddenly 1080p60 videos are being played in 720p30

### ISSUE THREAD

**Issue by wesley9946** [jdf76/plugin.video.youtube#240] opened 2018-01-13 18:00 UTC
Hi there,

A few days later after version 5.4.5 came along, 1080p@60fps videos are now being played at 720p@30fps all of a sudden
I tried setting everything to 1080p and played around with the minimal bandwidth, no luck.

Can you do something about it?

Thanks in advance!

**Comment by anxdpanic** [comment] 2018-01-13 18:06
Install https://github.com/jdf76/plugin.video.youtube/releases/tag/5.5.0-alpha and enable the proxy in Settings -> MPEG-DASH . Dash vods are not working in 5.4.5

**Comment by wesley9946** [comment] 2018-01-13 18:49
Thank you very much for the problem solving answer!

**Comment by crazy888** [comment] 2018-01-16 12:33
Hi. Im using this Plugin on my Nvidia Shield with SPMC16.7.2

Turning on Dash Proxy only brings a long waiting time before video starts but it is still 720p only.
What i´m doing wrong? Is it working for you?

**Comment by anxdpanic** [comment] 2018-01-16 13:10
@crazy888 can you provide a debug log, spmc handles dash differently than Kodi.

**Comment by crazy888** [comment] 2018-01-16 23:12
Of course.......
Here you are:
[https://pastebin.com/GbBpzXZE](url)

**Comment by anxdpanic** [comment] 2018-01-16 23:38
Thanks @crazy888 Can you redo that with debug logging enabled? Should hopefully shed some more light on the cause.

**Comment by crazy888** [comment] 2018-01-17 08:54
@anxdpanic  Find it here:
[http://paste.semperpax.com/poruxc5cl](http://paste.semperpax.com/poruxc5cl)

**Comment by anxdpanic** [comment] 2018-01-17 14:56
Looks like the dash manifest is not supported by SPMC. So for now dash will not work in SPMC, wish I had better news.

**Comment by crazy888** [comment] 2018-01-17 15:39
Jep, that are very bad news indeed.

I have startet a ticket at SPMC side.

Is there no way to add this manifest support into SPMC????

**Comment by anxdpanic** [comment] 2018-01-17 15:44
Not sure, I'm not familiar with SPMC's implementation of dash, and the spmc support in the add-on was added by another dev.

**Comment by Twilight0** [comment] 2018-01-18 10:22
Perhaps if we allow SPMC to load the manifest from filesystem instead of the proxy?

**Comment by anxdpanic** [comment] 2018-01-18 12:18
Doesn't work direct from filesystem either

**Comment by anxdpanic** [comment] 2018-01-20 15:48
Closing this issue, as it's been resolved. I have opened an SPMC specific issue. #258

**Closed by anxdpanic** 2018-01-20 15:48 UTC
