### ISSUE TITLE
Unable to open My Subscriptions, datetime parse error

### ISSUE THREAD

**Issue by philpem** [jdf76/plugin.video.youtube#799] opened 2020-04-24 11:20 UTC
When opening "My Subscriptions", I get an error telling me to check the Kodi log. Inside the log I found this:

```
2020-04-24 12:13:07.020 T:140183900104448   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/
2020-04-24 12:13:07.032 T:140185693735040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/) failed
2020-04-24 12:13:13.784 T:140183858140928  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.6) with Python 2.7.16
                                            	Path: /special/new_uploaded_videos_tv/
                                            	Params: {}
2020-04-24 12:13:15.540 T:140183858140928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data u'2020-04-24T10:53:35Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 781, in _on_yt_specials
                                                return yt_specials.process(category, self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 318, in process
                                                return _process_new_uploaded_videos_tv(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 285, in _process_new_uploaded_videos_tv
                                                result.extend(tv.my_subscriptions_to_items(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tv.py", line 56, in my_subscriptions_to_items
                                                utils.update_video_infos(provider, context, video_id_dict, channel_items_dict=channel_item_dict, use_play_data=use_play_data)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 292, in update_video_infos
                                                video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt']))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/datetime_parser.py", line 176, in strptime
                                                return datetime(*time.strptime(s, fmt)[:6])
                                              File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                            ValueError: time data u'2020-04-24T10:53:35Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            -->End of Python script error report<--
2020-04-24 12:13:15.717 T:140183900104448   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/
2020-04-24 12:13:15.733 T:140185693735040   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/) failed
```

It looks like the date/time format has changed.

This works okay as a workaround:

```
        # date time                                                   
        if not datetime and 'publishedAt' in snippet and snippet['publishedAt']:
            try:                                                          
                datetime = utils.datetime_parser.parse(snippet['publishedAt'])              
            except ValueError:                                                              
                datetime = utils.datetime_parser.parse(snippet['publishedAt'], fmt="%Y-%m-%dT%H:%M:%SZ")
            video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt']))
```
(note the addition of the try-except block)

This is in plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py

**Comment by philpem** [comment] 2020-04-24 11:48
I've just had this in the channel browser too (search for 'w2aew', pick Channels, pick 'w2aew).

Fixing datetime_parser.strptime might be a better fix:

```
    fmts = (                                                 
        "%Y-%m-%dT%H:%M:%S.%fZ",                             
        "%Y-%m-%dT%H:%M:%SZ"                                                                                      
        )                                                                                               
                                                                                                                                                                             
    for f in fmts:                                                                                                                                        
        try:                                                                                                                            
            return datetime(*time.strptime(s, f)[:6])                                                     
        except ValueError:                                                                                
            continue                                                                                      
    raise ValueError("Could not parse datetime '%s' using any known format" % s)     
```

**Comment by anxdpanic** [comment] 2020-04-24 15:28
Duplicate of #783 
Fixed in beta1 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev

**Closed by anxdpanic** 2020-04-24 15:28 UTC
