### ISSUE TITLE
Phyton error, youtube crash

### ISSUE THREAD

**Issue by faltaren** [jdf76/plugin.video.youtube#802] opened 2020-04-25 04:43 UTC
[kodi.log](https://github.com/jdf76/plugin.video.youtube/files/4532357/kodi.log)
Hey! I have the latest kodiu 18.7 nightly. Can browse my subcriptions without a crash. Plz chech the log.

**Comment by anxdpanic** [comment] 2020-04-25 20:40
Duplicate of #783 
Fixed in beta1 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev

**Closed by anxdpanic** 2020-04-25 20:40 UTC
