### ISSUE TITLE
Error (kodi.log)

### ISSUE THREAD

**Issue by drrak** [jdf76/plugin.video.youtube#798] opened 2020-04-24 05:30 UTC
_RPi4, Kodi 18.6, YT 6.7.0, LibreELEC 9.2.1_
```
020-04-24 07:14:53.560 T:3012022288  NOTICE: Running the application...
2020-04-24 07:14:53.572 T:3012022288  NOTICE: starting zeroconf publishing
2020-04-24 07:14:53.576 T:3012022288  NOTICE: CWebServer[8080]: Started
2020-04-24 07:14:53.578 T:2758206320  NOTICE: ES: Starting UDP Event server on port 9777
2020-04-24 07:14:53.578 T:2758206320  NOTICE: UDP: Listening on port 9777 (ipv6 : false)
2020-04-24 07:14:53.942 T:2845848432  NOTICE: Register - new cec device registered on cec->RPI: CEC Adapter (2708:1001)
2020-04-24 07:15:05.690 T:2572149616  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.6) with Python 2.7.16
                                            	Path: /
                                            	Params: {}
2020-04-24 07:15:13.022 T:2572149616  NOTICE: [plugin.video.youtube] Running: YouTube (6.7.0) on Leia (Kodi-18.6) with Python 2.7.16
                                            	Path: /special/new_uploaded_videos_tv/
                                            	Params: {}
2020-04-24 07:15:15.359 T:2572149616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: time data u'2020-04-23T20:38:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/default.py", line 15, in <module>
                                                runner.run(__provider__)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/runner.py", line 60, in run
                                                __RUNNER__.run(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/impl/xbmc/xbmc_runner.py", line 33, in run
                                                results = provider.navigate(context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/abstract_provider.py", line 100, in navigate
                                                result = method(context, re_match)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/register_provider_path.py", line 19, in wrapper
                                                return func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/provider.py", line 781, in _on_yt_specials
                                                return yt_specials.process(category, self, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 318, in process
                                                return _process_new_uploaded_videos_tv(provider, context)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/yt_specials.py", line 285, in _process_new_uploaded_videos_tv
                                                result.extend(tv.my_subscriptions_to_items(provider, context, json_data))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/tv.py", line 56, in my_subscriptions_to_items
                                                utils.update_video_infos(provider, context, video_id_dict, channel_items_dict=channel_item_dict, use_play_data=use_play_data)
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/youtube/helper/utils.py", line 292, in update_video_infos
                                                video_item.set_aired_utc(utils.datetime_parser.strptime(snippet['publishedAt']))
                                              File "/storage/.kodi/addons/plugin.video.youtube/resources/lib/youtube_plugin/kodion/utils/datetime_parser.py", line 176, in strptime
                                                return datetime(*time.strptime(s, fmt)[:6])
                                              File "/usr/lib/python2.7/_strptime.py", line 478, in _strptime_time
                                              File "/usr/lib/python2.7/_strptime.py", line 332, in _strptime
                                            ValueError: time data u'2020-04-23T20:38:01Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
                                            -->End of Python script error report<--
2020-04-24 07:15:15.427 T:2580542320   ERROR: GetDirectory - Error getting plugin://plugin.video.youtube/special/new_uploaded_videos_tv/
2020-04-24 07:15:15.445 T:3012022288   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.youtube/special/new_uploaded_videos_tv/) failed
```

**Comment by anxdpanic** [comment] 2020-04-24 05:32
Duplicate of #783 
This is fixed in beta1, https://github.com/jdf76/plugin.video.youtube/releases/tag/6.7.1-dev

**Closed by anxdpanic** 2020-04-24 05:32 UTC
