### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by pannal** [jdf76/plugin.video.youtube#313] opened 2018-03-23 02:06 UTC
Hey, 

Thank you for this great plugin, I really enjoy using it with kodi. 

As far as I can tell there is no progress handling in the plugin itself, it doesn't show any progress indicators nor does it allow me to resume playback on items that were not fully watched before. 

Am I doing something wrong or is this the current state? Can something be done about this? 

Thank you!

**Comment by anxdpanic** [comment] 2018-03-23 12:37
This is on the todo, believe it will require an additional database to track that information.

**Comment by greystashh** [comment] 2018-04-06 16:01
Didnt it work in the past? Has there been changes with the API to do not track this anymore?

**Comment by anxdpanic** [comment] 2018-04-06 16:12
The jsonrpc api doesn't allow updating this info for plugin urls iirc, which is why the additional database would be required. Though I'm not sure at what point the standard behavior changed(addon/kodi version), so I still need to look into some more.

**Comment by anxdpanic** [comment] 2018-06-10 16:00
I've added a playback history that uses custom mark (un)watched/resume points in d73970e5f092fd4c03688e20c2a021d785fce552
[add] Playback history (default: off) Settings -> Advanced -> Use playback history
Available in ~alpha7 https://github.com/jdf76/plugin.video.youtube/releases/tag/6.1.0-dev

**Comment by anxdpanic** [comment] 2018-07-30 13:55
Closing duplicate of #339

**Closed by anxdpanic** 2018-07-30 13:55 UTC
